### PR TITLE
Event System and Abstractions

### PR DESCRIPTION
**Pull request by steven4547466**
Adds a potential event system. Two example events to show how they would be implemented: `Player.Joined` and `Player.Left`. Also has potential abstractions.

Example connection:

```cs
LC_API.GameInterfaceAPI.Events.Handlers.Player.Joined += Joined;
LC_API.GameInterfaceAPI.Events.Handlers.Player.Left += Left;

// Somewhere else in the code:
public void Joined(PlayerJoinedEventArgs ev)
{
    Log.LogInfo("PLAYER JOINED");
    Log.LogInfo(ev.Player.playerSteamId);
}

public void Left(PlayerLeftEventArgs ev)
{
    Log.LogInfo("PLAYER LEFT");
    Log.LogInfo(ev.Player.playerSteamId);
}

// ------

// To disconnect:
LC_API.GameInterfaceAPI.Events.Handlers.Player.Joined -= Joined;
LC_API.GameInterfaceAPI.Events.Handlers.Player.Left -= Left;
```

### CODE REVIEW

**Comment by steven4547466** [comment]
Due to the way players are handled, the joined and left events require a cache of ids to ensure there's no double firing.

**Comment by steven4547466** [comment]
This is open to feedback on implementation if anyone has any ideas or thoughts, please let me know.

**Comment by legoandmars** [comment]
The implementation seems good to me, having some basic events based on common game occurrences would be very nice

**Comment by legoandmars** [comment]
Out of curiosity, is there a reason you're applying the harmony patch like that instead of just doing `Assembly.GetExecutingAssembly()`?

**Comment by steven4547466** [comment]
> Out of curiosity, is there a reason you're applying the harmony patch like that instead of just doing `Assembly.GetExecutingAssembly()`?

The current implementation of patches in this project were doing them by getting the original method directly, but if we have events, there will be too many to patch and it'll just be a big mess.

Technically `Harmony.PatchAll()` is what I'd normally use to just patch everything, but I wasn't sure if 2018 wanted to do that. So instead I just patch everything under the patches namespace.

If you're wondering why I do it like that, it's because `Harmony.PatchAll()` does this exactly, and I just added the namespace condition.

```cs
public void PatchAll()
{
    var method = new StackTrace().GetFrame(1).GetMethod();
    var assembly = method.ReflectedType.Assembly;
    PatchAll(assembly);
}
```

https://github.com/pardeike/Harmony/blob/c6e42d8b340d5b972ea2e8df5c46ba798fae7ce4/Harmony/Public/Harmony.cs#L74C1-L79C4

**Comment by steven4547466** [comment]
Please see new push and give feedback

**Comment by steven4547466** [comment]
Still working on this.

**Comment by steven4547466** [comment]
Latest commits has hurting and dying events

**Comment by steven4547466** [comment]
This will be merged by the end of the night if there are no problems with it

**Pull request merged**
